name = "advent_of_code"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.65.0 and < 2.0.0"
gladvent = ">= 2.2.0 and < 3.0.0"
parallel_map = ">=3.0.2 and < 4.0.0"
gleam_community_maths = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[gladvent.2023.1]
pt_1 = 54877
pt_2 = 54100

[gladvent.2023.2]
pt_1 = 2679
pt_2 = 77607

[gladvent.2023.3]
pt_1 = 538046
pt_2 = 81709807

[gladvent.2023.4]
pt_1 = 24160
pt_2 = 5659035

[gladvent.2023.5]
pt_1 = 178159714

[gladvent.2024.1]
pt_1 = 2367773
pt_2 = 21271939

[gladvent.2024.2]
pt_1 = 472
pt_2 = 520

[gladvent.2024.3]
pt_1 = 169021493
pt_2 = 111762583

[gladvent.2024.4]
pt_1 = 2500
pt_2 = 1933

[gladvent.2024.5]
pt_1 = 5268
pt_2 = 5799

[gladvent.2024.6]
pt_1 = 4665
pt_2 = 1688

[gladvent.2024.7]
pt_1 = 1620690235709
pt_2 = 145397611075341

[gladvent.2024.8]
pt_1 = 394
pt_2 = 1277

[gladvent.2024.9]
pt_1 = 6415184586041
pt_2 = 6436819084274

[gladvent.2024.10]
pt_1 = 512
pt_2 = 1045

[gladvent.2024.11]
pt_1 = 199753
pt_2 = 239413123020116

[gladvent.2024.12]
pt_1 = 1319878
pt_2 = 784982

[gladvent.2024.13]
pt_1 = 37901
pt_2 = 77407675412647

[gladvent.2024.14]
pt_1 = 217328832
pt_2 = 7412

[gladvent.2024.15]
pt_1 = 1552879

[gladvent.2025.1]
pt_1 = 1052
pt_2 = 6295

[gladvent.2025.2]
pt_1 = 24043483400
pt_2 = 38262920235

[gladvent.2025.3]
pt_1 = 17092

[gladvent.2025.4]
pt_1 = 1587
pt_2 = 8946
